### PR TITLE
Don't use {$base_url}

### PR DESCRIPTION
**Pull request by okom3pom**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | {$base_url} is not https
| Type?         | bug fix 
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20878.

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I'm afraid about relatives URLs :/ The problem is maybe the `$base_url` must be in https when the current domain is in https

**Comment by okom3pom** [comment]
I aggre @PierreRambaud but {$urls.xxx} is not availble on the back office which way you propose.

I can add _MODULE_DIR_ to smarty ?

**Comment by okom3pom** [comment]
if i follow you the best way is to change this line ? 

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/AdminController.php#L2037

**Comment by PierreRambaud** [comment]
> if i follow you the best way is to change this line ?
> 
> https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/AdminController.php#L2037

Yes by doing this I think:

```php
'base_url' => $this->context->shop->getBaseURL(true) ,
```

**Comment by okom3pom** [comment]
Ok i make a Pr and i close this one.

**Pull request closed without merging**
