### PR TITLE
Support of 1.6.1.x releases

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by marionf** [comment]
Every time I reinstall the module a new tab is created and I don't see any badge

capture d ecran_515

**Comment by mickaelandrieu** [comment]
It should work now... but you need to reload the page and/or clear the cache.

ps1 6

**Comment by marionf** [comment]
I can't reproduce anymore the issue of duplicated tabs but I have a weird behavior with badges after Unintall/reinstall and reset the module. It seems badges are not really removed when the module is reseted or uninstalled.
My smarty cache is disabled and I am in private navigation but every time I reset the module old badges are back

https://drive.google.com/open?id=1Gbt-AjeeunKHkAEqyH1xY1CN6dB5Quur

**Comment by mickaelandrieu** [comment]
Yes, it is expected (or not?): this data comes from the gamification server, when you uninstall the module, the information about your badges are not deleted by the server.

So even if you install a new shop with your prestashop account, I'm pretty sure you will retrieve your "experience" in ecommerce.

Is it a new behavior compared to the current version of gamification?

**Comment by marionf** [comment]
I don't know what is the behavior excpected, nothing is specified about this module. It was already like this before your change, so no issue.
Just I find it strange comapred to the behavior of other modules for which the data are deleted when you reset/uninstall it
So, maybe we should think about it

**Comment by mickaelandrieu** [comment]
> So, maybe we should think about it

I agree, I was wondering about GDPR but it's not really personal information...

**Pull request merged**
