### PR TITLE
Update logo and About section of README

### PR DESCRIPTION
**Pull request by Julievrz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Update logo and About section of README
| Type?         | improvement 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/15858
| How to test?  | Please check that the logo and the About section of README are updated.

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by PierreRambaud** [comment]
The code seems to be broken with composer v2 :(

**Comment by matks** [comment]
> The code seems to be broken with composer v2 :(

Need php-cs-fixer upgrade 2.15.1 => 2.16.4

**Comment by Progi1984** [comment]
@matks #77

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @Julievrz

**Pull request merged**
