### PR TITLE
Happy new year 2019

### PR DESCRIPTION
**Pull request by MathiasReker**
JS and CSS files has no change other than CR LF to LF. I use sed to replace. The lineending is for some reason changed due to this use.

### CODE REVIEW

**Comment by MathiasReker** [comment]
Yes, I need to find a solution for that. I use sed and sed does replace CR LF with LF.

`updateYear() {
  {
  PR_HAS_CHANGES=0
  NEW_YEAR=`date +'%Y'`
  BRANCH_NAME="happy-new-year-$NEW_YEAR"
  if [[ ! `git branch --list "$BRANCH_NAME"` ]]; then
    git checkout "$MASTER_BRANCH"
    git checkout -b "$BRANCH_NAME"
    array=('PHP' 'JS' 'TXT' 'TPL' 'CSS' 'SCSS' 'MD' 'TWIG' 'VUE')
    for FILE_TYPES in "${array[@]}"
    do
      OLD_YEAR=2013 #could be last year
      while [[ $OLD_YEAR < $NEW_YEAR ]]; do
        find ./ -iname "*.$FILE_TYPES" -exec sed -i "/$OLD_YEAR PrestaShop/ s/$OLD_YEAR PrestaShop/$NEW_YEAR PrestaShop/g" '{}' ';'
        OLD_YEAR=`expr $OLD_YEAR + 1`
      done
      if ! git diff-index --quiet HEAD --; then
        git add -A
        git commit -m "Update licens of $FILE_TYPES files"
        PR_HAS_CHANGES=1
      fi
    done
    if [[ $PR_HAS_CHANGES = 1 ]]; then
      git push origin "$BRANCH_NAME"
    else
      git checkout "$MASTER_BRANCH"
      git branch -D "$BRANCH_NAME"
    fi
  fi
  git checkout "$MASTER_BRANCH"
  } >/dev/null 2>&1
  echo ""
  if [[ $PR_HAS_CHANGES = 1 ]]; then
  echo -e "New branch: ${C_DODGERBLUE1}$BRANCH_NAME${NO_FORMAT}"
  echo ""
fi
  echo -e "${C_GREEN1}Done!${NO_FORMAT}"
}`

**Comment by MathiasReker** [comment]
does PrestaShop already have a script to replace date?

**Comment by PierreRambaud** [comment]
Yes we have something, the UpdateLicensesCommand.php

**Comment by Setax2** [comment]
Dear,
First, thank you all for your work. I am using this module in my store and I really like it.
I would like to ask you what is the best way to increase loyalty points from third party module. Ihave created a rewar called "Reward for review" with 200 points for leaving a review and I want to activate this if a customer leaves any review on another module. Is there an easy way to do it.
Thank you in advance and sorry if this is not the best place to ask this.
Best regards,

**Comment by Progi1984** [comment]
Thanks you @MathiasReker. I must close this PR because it doesn't bring any value.

**Pull request closed without merging**
